// src/pages/EmployerJobBids.tsx
// src/pages/EmployerJobBids.tsx
import { useEffect, useState } from "react";
import {
  Container,
  Typography,
  Grid,
  Card,
  CardContent,
  CardActions,
  Paper,
  Avatar,
  Box,
  Rating,
  Button,
} from "@mui/material";
import { useParams, useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import api from "../api";
import { Job } from "../entities/job";
import { Bid } from "../entities/bid";

const EmployerJobBids = () => {
  const { id } = useParams<{ id: string }>(); // job id from URL
  const [job, setJob] = useState<Job | null>(null);
  const [bids, setBids] = useState<Bid[]>([]);
  const [contract, setContract] = useState<any | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    if (id) {
      // Fetch job details
      api
        .get(`/jobs/${id}`)
        .then((response) => {
          const { job, bids, contract } = response.data.data;
          setJob(job);
          setBids(bids || []);
          setContract(contract || null);
        })
        .catch((error) => {
          console.error("Error fetching job details:", error);
          toast.error("Failed to fetch job details.");
        });
    }
  }, [id]);

  const handleFreelancerClick = (freelancerId: number) => {
    navigate(`/profile/${freelancerId}`);
  };

  const updateBidStatus = async (bidId: number, status: string) => {
    try {
      if (status === "rejected") {
        await api.put(`/job-bids/${bidId}/status`, { status });
        toast.success(`Bid ${status} successfully.`);
        setBids((prevBids) =>
          prevBids.map((bid) => (bid.id === bidId ? { ...bid, status } : bid))
        );
      }
      if (status === "accepted") {
        navigate(`/create-contract/${bidId}`);
      }
    } catch (error) {
      console.error("Error updating bid status:", error);
      toast.error("Failed to update bid status.");
    }
  };

  return (
    <Container sx={{ mt: 4 }}>
      {job ? (
        <Paper sx={{ p: 3, mb: 4, borderRadius: 2, boxShadow: 3 }}>
          <Typography variant="h4" gutterBottom>
            {job.jobTitle}
          </Typography>
          <Typography variant="body1" sx={{ mb: 1 }}>
            {job.jobDescription}
          </Typography>
          <Typography variant="subtitle1" sx={{ mb: 1 }}>
            Budget: {job.budget}
          </Typography>
          <Typography variant="subtitle2" color="text.secondary">
            Deadline: {job.deadline?.join("-")}
          </Typography>
        </Paper>
      ) : (
        <Typography>Loading job details...</Typography>
      )}

      <Typography variant="h5" gutterBottom>
        Bids for this Job
      </Typography>
      {bids.length > 0 ? (
        <Grid container spacing={3}>
          {bids.map((bid) => (
            <Grid item key={bid.id} xs={12} sm={6} md={4}>
              <Card sx={{ borderRadius: 2, boxShadow: 2, cursor: "pointer" }}>
                <CardContent
                  onClick={() =>
                    bid.freelancer.id !== undefined &&
                    handleFreelancerClick(bid.freelancer.id)
                  }
                >
                  <Typography variant="h6">
                    Bid Amount: {bid.bidAmount}
                  </Typography>
                  <Typography variant="body2" sx={{ mt: 1 }}>
                    Deposit Amount: {bid.depositAmount || "Not specified"}
                  </Typography>
                  <Typography variant="body2" sx={{ mt: 1 }}>
                    Final Payment: {bid.finalPaymentAmount || "Not specified"}
                  </Typography>

                  <Typography variant="body2" sx={{ mt: 1 }}>
                    Message: {bid.message}
                  </Typography>
                  {bid.proposedStartDate && bid.proposedEndDate && (
                    <Typography variant="body2" sx={{ mt: 1 }}>
                      Proposed Period:&nbsp;
                      {new Date(
                        bid.proposedStartDate[0],
                        bid.proposedStartDate[1] - 1,
                        bid.proposedStartDate[2]
                      ).toLocaleDateString()}
                      &nbsp;to&nbsp;
                      {new Date(
                        bid.proposedEndDate[0],
                        bid.proposedEndDate[1] - 1,
                        bid.proposedEndDate[2]
                      ).toLocaleDateString()}
                    </Typography>
                  )}
                  {bid.supportAvailability && (
                    <Typography variant="body2" sx={{ mt: 1 }}>
                      Support: {bid.supportAvailability}
                    </Typography>
                  )}
                  {bid.additionalPolicy && (
                    <Typography variant="body2" sx={{ mt: 1 }}>
                      Policy: {bid.additionalPolicy}
                    </Typography>
                  )}
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    sx={{ mt: 1 }}
                  >
                    Status: {bid.status}
                  </Typography>
                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      mt: 2,
                      cursor: "pointer",
                    }}
                  >
                    {bid.freelancer.profilePictureUrl ? (
                      <Avatar
                        src={bid.freelancer.profilePictureUrl}
                        alt={bid.freelancer.fullName}
                        sx={{ mr: 1 }}
                      />
                    ) : (
                      <Avatar sx={{ mr: 1 }}>
                        {(bid.freelancer.fullName ?? "")
                          .split(" ")
                          .map((n) => n.charAt(0))
                          .join("")}
                      </Avatar>
                    )}
                    <Box>
                      <Typography variant="subtitle2">
                        {bid.freelancer.fullName}
                      </Typography>
                      {bid.freelancer.rating !== null &&
                      bid.freelancer.rating !== undefined ? (
                        <Box sx={{ display: "flex", alignItems: "center" }}>
                          <Rating
                            name="read-only"
                            value={Number(bid.freelancer.rating)}
                            precision={0.1}
                            readOnly
                            size="small"
                          />
                          <Typography variant="body2" sx={{ ml: 0.5 }}>
                            {bid.freelancer.rating.toFixed(1)}
                          </Typography>
                        </Box>
                      ) : (
                        <Typography variant="body2">No rating</Typography>
                      )}
                    </Box>
                  </Box>
                </CardContent>
                {!contract && bid.status === "pending" && (
                  <CardActions sx={{ justifyContent: "space-between" }}>
                    <Button
                      size="small"
                      variant="contained"
                      color="success"
                      onClick={(e) => {
                        e.stopPropagation();
                        updateBidStatus(bid.id, "accepted");
                      }}
                    >
                      Accept & Create Contract
                    </Button>
                    <Button
                      size="small"
                      variant="contained"
                      color="error"
                      onClick={(e) => {
                        e.stopPropagation();
                        updateBidStatus(bid.id, "rejected");
                      }}
                    >
                      Reject
                    </Button>
                  </CardActions>
                )}
              </Card>
            </Grid>
          ))}
        </Grid>
      ) : (
        <Typography>No bids for this job yet.</Typography>
      )}
    </Container>
  );
};

export default EmployerJobBids;

// src/app/pages/employer/employer-job-bids/employer-job-bids.component.ts
// src/app/pages/employer/employer-job-bids/employer-job-bids.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { Job } from '../../../models/job';
import { Bid } from '../../../models/bid';
import { Milestone } from '../../../models/milestone';
import { ApiService } from '../../../services/api.service';
import { ToastService } from '../../../services/toast.service';

// Material imports
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatGridListModule } from '@angular/material/grid-list';
import { MatDividerModule } from '@angular/material/divider';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatChipsModule } from '@angular/material/chips';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatBadgeModule } from '@angular/material/badge';

@Component({
  selector: 'app-employer-job-bids',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatButtonModule,
    MatGridListModule,
    MatDividerModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatExpansionModule,
    MatProgressBarModule,
    MatTooltipModule,
    MatBadgeModule
  ],
  templateUrl: './employer-job-bids.component.html',
  styleUrls: ['./employer-job-bids.component.scss']
})
export class EmployerJobBidsComponent implements OnInit {
  job: Job | null = null;
  bids: Bid[] = [];
  contract: any | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiService: ApiService,
    private toastService: ToastService
  ) {}

  ngOnInit(): void {
    this.route.paramMap.subscribe(params => {
      const id = params.get('id');
      if (id) {
        this.fetchJobDetails(id);
      }
    });
  }

  fetchJobDetails(jobId: string): void {
    this.apiService.get<any>(`/jobs/${jobId}`)
      .subscribe({
        next: (response) => {
          const { job, bids, contract } = response.data;
          this.job = job;
          this.bids = bids || [];
          this.contract = contract || null;
        },
        error: (error) => {
          console.error('Error fetching job details:', error);
          this.toastService.error('Failed to fetch job details.');
        }
      });
  }

  handleFreelancerClick(freelancerId: number): void {
    this.router.navigate(['/profile', freelancerId]);
  }

  updateBidStatus(event: Event, bidId: number, status: string): void {
    event.stopPropagation(); // Prevent card onClick
    
    if (status === 'rejected') {
      this.apiService.put<any>(`/job-bids/${bidId}/status`, { status })
        .subscribe({
          next: () => {
            this.toastService.success(`Bid ${status} successfully.`);
            this.bids = this.bids.map(bid => 
              bid.id === bidId ? { ...bid, status } : bid
            );
          },
          error: (error) => {
            console.error('Error updating bid status:', error);
            this.toastService.error('Failed to update bid status.');
          }
        });
    } else if (status === 'accepted') {
      // Navigate to create-contract with the bid id
      this.router.navigate(['/create-contract', bidId]);
    }
  }

  getMilestoneStatus(milestone: Milestone): string {
    if (milestone.reviewStatus === 'approved') return 'completed';
    if (milestone.deliverableUrl) return 'submitted';
    
    // Safely handle different possible types for dueDate
    let dueDate: Date;
    if (Array.isArray(milestone.dueDate)) {
      // Handle if it's an array of numbers [year, month, day]
      dueDate = new Date(
        milestone.dueDate[0],
        milestone.dueDate[1] - 1,
        milestone.dueDate[2]
      );
    } else if (typeof milestone.dueDate === 'string') {
      // Handle if it's a string date
      dueDate = new Date(milestone.dueDate);
    } else {
      // Fallback to current date if undefined or invalid
      dueDate = new Date();
    }
    
    if (dueDate < new Date()) return 'overdue';
    return 'pending';
  }

  getMilestoneStatusClass(milestone: Milestone): string {
    return `status-${this.getMilestoneStatus(milestone)}`;
  }

  getMilestoneStatusColor(milestone: Milestone): string {
    const status = this.getMilestoneStatus(milestone);
    switch (status) {
      case 'completed': return 'success';
      case 'submitted': return 'primary';
      case 'overdue': return 'warn';
      case 'pending': return 'accent';
      default: return 'default';
    }
  }

  getTotalEffort(): number {
    if (!this.job || !this.job.milestones || this.job.milestones.length === 0) {
      return 0;
    }
    return this.job.milestones.reduce((sum, ms) => sum + (ms.effort || 0), 0);
  }

  getTotalAmount(): number {
    if (!this.job || !this.job.milestones || this.job.milestones.length === 0) {
      return this.job?.budget || 0;
    }
    return this.job.milestones.reduce((sum, ms) => sum + (ms.amount || 0), 0);
  }

  getPaymentPercentage(milestone: Milestone): string {
    const totalAmount = this.getTotalAmount();
    if (totalAmount === 0) return '0';
    return (((milestone.amount || 0) / totalAmount) * 100).toFixed(1);
  }

  getBidStatusColor(status: string): string {
    switch (status) {
      case 'accepted': return 'success';
      case 'rejected': return 'warn';
      default: return 'default';
    }
  }

  formatDate(dateValue?: string | number[]): string {
    if (!dateValue) return 'Invalid date';
    
    let date: Date;
    
    if (Array.isArray(dateValue)) {
      // Handle array format [year, month, day]
      if (dateValue.length < 3) return 'Invalid date';
      date = new Date(dateValue[0], dateValue[1] - 1, dateValue[2]);
    } else if (typeof dateValue === 'string') {
      // Handle string date
      date = new Date(dateValue);
    } else {
      return 'Invalid date';
    }
    
    // Check if date is valid
    if (isNaN(date.getTime())) {
      return 'Invalid date';
    }
    
    return date.toLocaleDateString();
  }

  getInitials(name: string): string {
    return name
      .split(' ')
      .map(n => n.charAt(0))
      .join('');
  }

  getStars(rating: number): number[] {
    return Array(5).fill(0).map((_, index) => index + 1);
  }
}
<!-- src/app/pages/employer/employer-job-bids/employer-job-bids.component.html -->
<div class="container">
  <ng-container *ngIf="job; else loadingJob">
    <div class="job-details">
      <h2 class="job-title">{{ job.jobTitle }}</h2>
      <p class="job-description">{{ job.jobDescription }}</p>
      
      <div class="job-meta">
        <mat-chip-listbox>
          <mat-chip color="primary" selected>Budget: ${{ job.budget?.toLocaleString() }}</mat-chip>
          <mat-chip color="accent" selected *ngIf="job.deadline">Deadline: {{ formatDate(job.deadline) }}</mat-chip>
          <mat-chip *ngIf="job.category">{{ job.category.name }}</mat-chip>
        </mat-chip-listbox>
      </div>
      
      <!-- Milestones Section -->
      <div class="milestones-section" *ngIf="job.milestones && job.milestones.length > 0">
        <h3 class="section-title">
          <mat-icon>assignment</mat-icon>
          Milestones
        </h3>
        
        <div class="milestones-container">
          <mat-accordion>
            <mat-expansion-panel 
              *ngFor="let milestone of job.milestones; let i = index" 
              [expanded]="i === 0" 
              class="milestone-panel"
              [ngClass]="getMilestoneStatusClass(milestone)"
            >
              <mat-expansion-panel-header>
                <mat-panel-title>
                  <div class="milestone-number">{{ i + 1 }}</div>
                  {{ milestone.title }}
                </mat-panel-title>
                <mat-panel-description>
                  <mat-chip-listbox>
                    <mat-chip 
                      [color]="getMilestoneStatusColor(milestone)" 
                      selected
                      size="small"
                    >
                      {{ getMilestoneStatus(milestone).toUpperCase() }}
                    </mat-chip>
                    <mat-chip 
                      [color]="getMilestoneStatusColor(milestone)"
                      selected
                      size="small"
                      outlined
                    >
                      {{ milestone.effort }}%
                    </mat-chip>
                  </mat-chip-listbox>
                </mat-panel-description>
              </mat-expansion-panel-header>
              
              <div class="milestone-details">
                <p class="milestone-description">{{ milestone.description }}</p>
                
                <div class="milestone-grid">
                  <div class="milestone-dates">
                    <h4>
                      <mat-icon>calendar_today</mat-icon>
                      Timeline
                    </h4>
                    <div class="milestone-date-info">
                      <p><strong>Start:</strong> {{ formatDate(milestone.startDate) }}</p>
                      <p><strong>Due:</strong> {{ formatDate(milestone.dueDate) }}</p>
                    </div>
                  </div>
                  
                  <div class="milestone-effort">
                    <h4>
                      <mat-icon>access_time</mat-icon>
                      Effort & Payment
                    </h4>
                    <div class="milestone-effort-info">
                      <p matTooltip="{{ milestone.effort }}% of total effort">
                        <strong>Effort:</strong> {{ milestone.effort }}%
                      </p>
                      <p matTooltip="{{ getPaymentPercentage(milestone) }}% of total budget">
                        <strong>Payment:</strong> ${{ milestone.amount?.toLocaleString() || '0' }}
                      </p>
                    </div>
                  </div>
                </div>
                
                <div class="milestone-checklist" *ngIf="milestone.checklist">
                  <h4>
                    <mat-icon>check</mat-icon>
                    Checklist
                  </h4>
                  <div class="checklist-content">
                    <div [innerHTML]="milestone.checklist"></div>
                  </div>
                </div>
              </div>
            </mat-expansion-panel>
          </mat-accordion>
          
          <mat-divider></mat-divider>
          
          <div class="milestone-summary">
            <div class="milestone-progress">
              <p>Total Progress: {{ getTotalEffort() }}%</p>
              <mat-progress-bar 
                mode="determinate" 
                [value]="getTotalEffort()" 
                class="progress-bar"
              ></mat-progress-bar>
            </div>
            
            <div class="milestone-budget">
              <p>Total Budget</p>
              <h3>${{ getTotalAmount().toLocaleString() }}</h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Bids Section -->
    <h3 class="section-title">Bids for this Job</h3>
    
    <div class="bids-container" *ngIf="bids.length > 0; else noBids">
      <div class="bids-grid">
        <div class="bid-card" *ngFor="let bid of bids">
          <mat-card (click)="handleFreelancerClick(bid.freelancer.id || 0)">
            <mat-card-content>
              <h3 class="bid-amount">Bid Amount: ${{ bid.bidAmount?.toLocaleString() }}</h3>
              
              <mat-chip-listbox>
                <mat-chip 
                  [color]="getBidStatusColor(bid.status)" 
                  selected
                >
                  Status: {{ bid.status }}
                </mat-chip>
              </mat-chip-listbox>
              
              <p class="bid-message"><strong>Message:</strong> {{ bid.message }}</p>
              
              <p class="bid-dates" *ngIf="bid.proposedStartDate && bid.proposedEndDate">
                <strong>Proposed Period:</strong>
                {{ formatDate(bid.proposedStartDate) }} to {{ formatDate(bid.proposedEndDate) }}
              </p>
              
              <p *ngIf="bid.supportAvailability">
                <strong>Support:</strong> {{ bid.supportAvailability }}
              </p>
              
              <p *ngIf="bid.additionalPolicy">
                <strong>Policy:</strong> {{ bid.additionalPolicy }}
              </p>
              
              <mat-divider></mat-divider>
              
              <div class="freelancer-info">
                <div class="freelancer-avatar">
                  <ng-container *ngIf="bid.freelancer.profilePictureUrl; else defaultAvatar">
                    <img 
                      [src]="bid.freelancer.profilePictureUrl" 
                      [alt]="bid.freelancer.fullName" 
                      class="avatar-img"
                    >
                  </ng-container>
                  <ng-template #defaultAvatar>
                    <div class="default-avatar">
                      {{ getInitials(bid.freelancer.fullName || '') }}
                    </div>
                  </ng-template>
                </div>
                
                <div class="freelancer-details">
                  <p class="freelancer-name">{{ bid.freelancer.fullName }}</p>
                  
                  <div class="freelancer-rating" *ngIf="bid.freelancer.rating !== null; else noRating">
                    <div class="star-rating">
                      <span 
                        *ngFor="let star of getStars(bid.freelancer.rating || 0)" 
                        class="star" 
                        [ngClass]="{'filled': star <= (bid.freelancer.rating || 0)}"
                      >
                        ★
                      </span>
                      <span class="rating-value">{{ bid.freelancer.rating?.toFixed(1) }}</span>
                    </div>
                  </div>
                  
                  <ng-template #noRating>
                    <p class="no-rating">No rating</p>
                  </ng-template>
                </div>
              </div>
            </mat-card-content>
            
            <mat-card-actions *ngIf="!contract && bid.status === 'pending'">
              <button 
                mat-raised-button 
                color="primary" 
                (click)="updateBidStatus($event, bid.id, 'accepted')"
              >
                Accept & Create Contract
              </button>
              <button 
                mat-stroked-button 
                color="warn" 
                (click)="updateBidStatus($event, bid.id, 'rejected')"
              >
                Reject
              </button>
            </mat-card-actions>
          </mat-card>
        </div>
      </div>
    </div>
    
    <ng-template #noBids>
      <div class="no-bids">
        <p>No bids for this job yet.</p>
      </div>
    </ng-template>
  </ng-container>
  
  <ng-template #loadingJob>
    <div class="loading-container">
      <mat-spinner diameter="40"></mat-spinner>
      <p>Loading job details...</p>
    </div>
  </ng-template>
</div>
