// src/app/pages/contract-detail/contract-detail.component.ts
// src/app/pages/contract-detail/contract-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { ToastService } from '../../services/toast.service';
import { AuthService } from '../../services/auth.service';
import { Contract } from '../../models/contract';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { provideNativeDateAdapter } from '@angular/material/core';

// Material imports
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatDividerModule } from '@angular/material/divider';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatChipsModule } from '@angular/material/chips';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatStepperModule } from '@angular/material/stepper';
import { MatGridListModule } from '@angular/material/grid-list';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatBadgeModule } from '@angular/material/badge';
import { MatSnackBarModule } from '@angular/material/snack-bar';

@Component({
  selector: 'app-contract-detail',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatCardModule,
    MatButtonModule,
    MatDividerModule,
    MatIconModule,
    MatProgressBarModule,
    MatChipsModule,
    MatTooltipModule,
    MatStepperModule,
    MatGridListModule,
    MatProgressSpinnerModule,
    MatBadgeModule,
    MatSnackBarModule
  ],
  providers: [
    provideNativeDateAdapter()
  ],
  templateUrl: './contract-detail.component.html',
  styleUrls: ['./contract-detail.component.scss']
})
export class ContractDetailComponent implements OnInit {
  contract: any = null;
  loading = true;
  user: any;
  isMobile = false;
  
  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiService: ApiService,
    private toastService: ToastService,
    private authService: AuthService,
    private breakpointObserver: BreakpointObserver
  ) {
    this.user = this.authService.currentUserValue;
    this.breakpointObserver.observe([Breakpoints.HandsetPortrait])
      .subscribe(result => {
        this.isMobile = result.matches;
      });
  }

  ngOnInit(): void {
    this.route.paramMap.subscribe(params => {
      const contractId = params.get('id');
      if (contractId) {
        this.fetchContractDetails(contractId);
      }
    });
  }

  fetchContractDetails(contractId: string): void {
    this.loading = true;
    this.apiService.get<any>(`/contracts/${contractId}`)
      .subscribe({
        next: (response) => {
          this.contract = response.data;
          this.loading = false;
        },
        error: (error) => {
          console.error('Error fetching contract:', error);
          this.toastService.error('Failed to load contract.');
          this.loading = false;
        }
      });
  }

  updateContractStatus(isAccepted: boolean): void {
    const contractId = this.route.snapshot.paramMap.get('id');
    if (!contractId) return;

    this.apiService.put<any>(`/contracts/${contractId}/status?isAccepted=${isAccepted}`, {})
      .subscribe({
        next: (response) => {
          this.contract = response.data;
          this.toastService.success(isAccepted ? 'Contract Accepted!' : 'Contract Rejected!');

          if (isAccepted && this.isEmployer()) {
            this.processPayment(contractId);
          }
        },
        error: (error) => {
          console.error('Error updating contract status:', error);
          this.toastService.error('Something went wrong.');
        }
      });
  }

  processPayment(contractId: string): void {
    this.apiService.post<any>(`/payment/contract/${contractId}`, {})
      .subscribe({
        next: () => {
          this.toastService.success('Payment processed successfully!');
        },
        error: (error) => {
          console.error('Error processing payment:', error);
          this.toastService.error('Failed to process payment.');
        }
      });
  }

  // Helper functions for the template
  formatDate(dateArr: number[]): string {
    if (!dateArr || dateArr.length < 3) return 'Invalid date';
    
    return new Date(
      dateArr[0],
      dateArr[1] - 1,
      dateArr[2],
      dateArr[3] || 0,
      dateArr[4] || 0
    ).toLocaleString();
  }

  getDaysBetween(startDate: number[], endDate: number[]): number {
    if (!startDate || !endDate) return 0;
    
    const start = new Date(startDate[0], startDate[1] - 1, startDate[2]);
    const end = new Date(endDate[0], endDate[1] - 1, endDate[2]);
    const diffTime = Math.abs(end.getTime() - start.getTime());
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  }

  calculateProgress(startDate: number[], endDate: number[]): number {
    if (!startDate || !endDate) return 0;
    
    const start = new Date(startDate[0], startDate[1] - 1, startDate[2]);
    const end = new Date(endDate[0], endDate[1] - 1, endDate[2]);
    const now = new Date();

    if (now < start) return 0;
    if (now > end) return 100;

    const totalDuration = end.getTime() - start.getTime();
    const elapsedDuration = now.getTime() - start.getTime();
    return Math.round((elapsedDuration / totalDuration) * 100);
  }

  getContractStatusInfo(status: string): { color: string, icon: string, step: number } {
    switch (status) {
      case 'ACTIVE':
        return { color: 'success', icon: 'check_circle', step: 2 };
      case 'NEGOTIATION':
        return { color: 'warn', icon: 'help_outline', step: 1 };
      case 'COMPLETED':
        return { color: 'primary', icon: 'assignment', step: 3 };
      case 'CANCELLED':
        return { color: 'error', icon: 'cancel', step: 1 };
      default:
        return { color: 'default', icon: 'info', step: 0 };
    }
  }

  getCurrentStep(): number {
    if (!this.contract) return 0;
    
    const { status, employerAccepted, freelancerAccepted } = this.contract;
    
    if (status === 'ACTIVE' || status === 'COMPLETED') return 3;
    if (employerAccepted && freelancerAccepted) return 2;
    if (employerAccepted) return 1;
    return 0;
  }

  isEmployer(): boolean {
    if (!this.contract || !this.user) return false;
    return this.user.id === this.contract.employer.id;
  }

  isFreelancer(): boolean {
    if (!this.contract || !this.user) return false;
    return this.user.id === this.contract.freelancer.id;
  }

  canEmployerAct(): boolean {
    if (!this.contract) return false;
    return this.isEmployer() && 
           this.contract.status === 'NEGOTIATION' && 
           !this.contract.employerAccepted;
  }

  canFreelancerAct(): boolean {
    if (!this.contract) return false;
    return this.isFreelancer() && 
           this.contract.status === 'NEGOTIATION' && 
           this.contract.employerAccepted && 
           !this.contract.freelancerAccepted;
  }

  navigateToContracts(): void {
    this.router.navigate(['/my-contracts']);
  }

  navigateToMilestones(): void {
    const contractId = this.route.snapshot.paramMap.get('id');
    if (contractId) {
      this.router.navigate(['/contract', contractId, 'milestones']);
    }
  }

  getInitials(name: string): string {
    if (!name) return '';
    
    return name
      .split(' ')
      .map(n => n.charAt(0))
      .join('')
      .toUpperCase();
  }
}
<!-- src/app/pages/contract-detail/contract-detail.component.html -->
<div class="container">
    <!-- Loading state -->
    <div *ngIf="loading" class="loading-container">
      <h2 class="loading-text">Loading Contract Details</h2>
      <mat-progress-bar mode="indeterminate" class="loading-progress"></mat-progress-bar>
    </div>
  
    <!-- Contract not found -->
    <div *ngIf="!loading && !contract" class="not-found-container">
      <h2 class="error-text">Contract not found</h2>
      <button mat-raised-button color="primary" (click)="navigateToContracts()">
        Back to Contracts
      </button>
    </div>
  
    <!-- Contract details -->
    <div *ngIf="!loading && contract" class="contract-container">
      <div class="header-section">
        <h1 class="main-title">Contract Details</h1>
        <p class="subtitle">Contract #{{ contract.id }} • {{ contract.status }}</p>
      </div>
  
      <!-- Contract Status & Approval Process -->
      <mat-card class="status-card">
        <div class="status-header" [ngClass]="'status-bg-' + getContractStatusInfo(contract.status).color">
          <div class="status-title">
            <mat-icon>{{ getContractStatusInfo(contract.status).icon }}</mat-icon>
            <span>Contract Status: {{ contract.status }}</span>
          </div>
          <mat-chip class="status-chip">{{ contract.contractType || 'Standard Contract' }}</mat-chip>
        </div>
  
        <div class="card-content">
          <mat-stepper [selectedIndex]="getCurrentStep()" linear #stepper>
            <mat-step>
              <ng-template matStepLabel>Employer Review</ng-template>
            </mat-step>
            <mat-step>
              <ng-template matStepLabel>Freelancer Review</ng-template>
            </mat-step>
            <mat-step>
              <ng-template matStepLabel>Contract Active</ng-template>
            </mat-step>
          </mat-stepper>
  
          <!-- Progress indicators -->
          <div class="progress-indicators">
            <div class="status-grid">
              <!-- Employer status -->
              <div class="status-item">
                <div class="status-box">
                  <p class="status-label">Employer</p>
                  <div class="status-value">
                    <mat-icon 
                      [color]="contract.employerAccepted === true ? 'success' : 
                                contract.employerAccepted === false ? 'warn' : 'warn'">
                      {{ contract.employerAccepted === true ? 'check_circle' : 
                         contract.employerAccepted === false ? 'cancel' : 'access_time' }}
                    </mat-icon>
                    <span 
                      [ngClass]="{
                        'success-text': contract.employerAccepted === true,
                        'error-text': contract.employerAccepted === false,
                        'warning-text': contract.employerAccepted === undefined || contract.employerAccepted === null
                      }">
                      {{ contract.employerAccepted === true ? 'Accepted' : 
                         contract.employerAccepted === false ? 'Rejected' : 'Pending' }}
                    </span>
                  </div>
                </div>
              </div>
  
              <!-- Freelancer status -->
              <div class="status-item">
                <div class="status-box">
                  <p class="status-label">Freelancer</p>
                  <div class="status-value">
                    <mat-icon 
                      [color]="contract.freelancerAccepted === true ? 'success' : 
                                contract.freelancerAccepted === false ? 'warn' : 'warn'">
                      {{ contract.freelancerAccepted === true ? 'check_circle' : 
                         contract.freelancerAccepted === false ? 'cancel' : 'access_time' }}
                    </mat-icon>
                    <span 
                      [ngClass]="{
                        'success-text': contract.freelancerAccepted === true,
                        'error-text': contract.freelancerAccepted === false,
                        'warning-text': contract.freelancerAccepted === undefined || contract.freelancerAccepted === null
                      }">
                      {{ contract.freelancerAccepted === true ? 'Accepted' : 
                         contract.freelancerAccepted === false ? 'Rejected' : 'Pending' }}
                    </span>
                  </div>
                </div>
              </div>
  
              <!-- Contract status -->
              <div class="status-item">
                <div class="status-box">
                  <p class="status-label">Contract Status</p>
                  <div class="status-value">
                    <mat-icon [color]="getContractStatusInfo(contract.status).color">
                      {{ getContractStatusInfo(contract.status).icon }}
                    </mat-icon>
                    <span [ngClass]="getContractStatusInfo(contract.status).color + '-text'">
                      {{ contract.status }}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
  
          <!-- Approval actions -->
          <div *ngIf="canEmployerAct() || canFreelancerAct()" class="approval-actions">
            <div class="alert info-alert">
              <p class="alert-message">
                {{ canEmployerAct() 
                   ? 'As the employer, you need to review and approve this contract.' 
                   : 'As the freelancer, you need to review and approve this contract.' }}
              </p>
              <div class="alert-buttons">
                <button mat-raised-button color="primary" (click)="updateContractStatus(true)">
                  <mat-icon>check</mat-icon>
                  Accept
                </button>
                <button mat-stroked-button color="warn" (click)="updateContractStatus(false)">
                  <mat-icon>close</mat-icon>
                  Reject
                </button>
              </div>
            </div>
          </div>
        </div>
      </mat-card>
  
      <div class="contract-details-grid">
        <!-- Left Column - Parties Information -->
        <div class="parties-container">
          <mat-card class="parties-card">
            <div class="card-header">
              <mat-icon color="primary">person</mat-icon>
              <span>Contract Parties</span>
            </div>
  
            <div class="card-content">
              <!-- Employer -->
              <div class="party-section">
                <h3 class="section-title">Employer</h3>
                <div class="party-info">
                  <div class="avatar employer-avatar">
                    {{ getInitials(contract.employer.fullName) }}
                  </div>
                  <div class="party-details">
                    <p class="name">{{ contract.employer.fullName }}</p>
                    <p class="email">{{ contract.employer.email }}</p>
                    <div class="status-tag">
                      <mat-chip 
                        [color]="contract.employerAccepted === true ? 'success' : 
                                  contract.employerAccepted === false ? 'warn' : 'warn'" 
                        class="mini-chip">
                        {{ contract.employerAccepted === true ? 'Accepted' : 
                           contract.employerAccepted === false ? 'Rejected' : 'Pending' }}
                      </mat-chip>
                    </div>
                  </div>
                </div>
              </div>
  
              <!-- Freelancer -->
              <div class="party-section">
                <h3 class="section-title">Freelancer</h3>
                <div class="party-info">
                  <div class="avatar freelancer-avatar">
                    {{ getInitials(contract.freelancer.fullName) }}
                  </div>
                  <div class="party-details">
                    <p class="name">{{ contract.freelancer.fullName }}</p>
                    <p class="email">{{ contract.freelancer.email }}</p>
                    <div class="status-tag">
                      <mat-chip 
                        [color]="contract.freelancerAccepted === true ? 'success' : 
                                  contract.freelancerAccepted === false ? 'warn' : 'warn'" 
                        class="mini-chip">
                        {{ contract.freelancerAccepted === true ? 'Accepted' : 
                           contract.freelancerAccepted === false ? 'Rejected' : 'Pending' }}
                      </mat-chip>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </mat-card>
        </div>
  
        <!-- Right Column - Contract Details -->
        <div class="details-container">
          <mat-card class="details-card">
            <div class="card-header">
              <mat-icon color="primary">assignment</mat-icon>
              <span>Contract Details</span>
            </div>
  
            <div class="card-content">
              <!-- Contract Period -->
              <div class="period-section">
                <h3 class="section-title">
                  <mat-icon>calendar_month</mat-icon>
                  Contract Period
                </h3>
  
                <div class="date-grid">
                  <div class="date-item">
                    <div class="date-box">
                      <span class="date-label">Start Date</span>
                      <span class="date-value">{{ formatDate(contract.contractStartDate) }}</span>
                    </div>
                  </div>
                  <div class="date-item">
                    <div class="date-box">
                      <span class="date-label">End Date</span>
                      <span class="date-value">{{ formatDate(contract.contractEndDate) }}</span>
                    </div>
                  </div>
                </div>
  
                <div class="progress-section">
                  <div class="progress-header">
                    <div class="progress-title">
                      <mat-icon>access_time</mat-icon>
                      <span>Contract Progress</span>
                    </div>
                    <span class="progress-value">
                      {{ calculateProgress(contract.contractStartDate, contract.contractEndDate) }}%
                    </span>
                  </div>
                  <mat-progress-bar 
                    mode="determinate" 
                    [value]="calculateProgress(contract.contractStartDate, contract.contractEndDate)"
                    class="contract-progress">
                  </mat-progress-bar>
                  <div class="days-count">
                    {{ getDaysBetween(contract.contractStartDate, contract.contractEndDate) }} total days
                  </div>
                </div>
              </div>
  
              <!-- Policy & Support -->
              <div class="policy-section">
                <h3 class="section-title">
                  <mat-icon>gavel</mat-icon>
                  Policy & Support
                </h3>
  
                <div *ngIf="contract.supportAvailability" class="policy-item">
                  <div class="policy-box">
                    <span class="policy-label">Support Availability</span>
                    <p class="policy-value">{{ contract.supportAvailability }}</p>
                  </div>
                </div>
  
                <div *ngIf="contract.additionalPolicy" class="policy-item">
                  <div class="policy-box">
                    <span class="policy-label">Additional Policy</span>
                    <p class="policy-value">{{ contract.additionalPolicy }}</p>
                  </div>
                </div>
              </div>
            </div>
          </mat-card>
        </div>
      </div>
  
      <!-- Action Buttons -->
      <div class="action-buttons">
        <div [class]="isMobile ? 'button-stack' : 'button-row'">
          <button 
            mat-stroked-button 
            color="primary" 
            (click)="navigateToContracts()"
            class="action-button back-button">
            <mat-icon class="rotate-180">arrow_forward</mat-icon>
            Back to Contracts
          </button>
  
          <button 
            *ngIf="contract.employerAccepted && contract.freelancerAccepted"
            mat-raised-button 
            color="primary" 
            (click)="navigateToMilestones()"
            class="action-button">
            View Milestones
            <mat-icon>arrow_forward</mat-icon>
          </button>
        </div>
      </div>
    </div>
  </div>

// src/pages/ContractDetail.tsx
import { useContext, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import {
  Container,
  Typography,
  Paper,
  Box,
  Grid,
  Chip,
  Divider,
  Button,
  Stack,
} from "@mui/material";
import api from "../api";
import { toast } from "react-toastify";
import { AuthContext } from "../context/AuthContext";

const formatDate = (dateArr: number[]) =>
  new Date(
    dateArr[0],
    dateArr[1] - 1,
    dateArr[2],
    dateArr[3],
    dateArr[4]
  ).toLocaleString();

const ContractDetail = () => {
  const { contractId } = useParams<{ contractId: string }>();
  const [contract, setContract] = useState<any>(null);
  const { user } = useContext(AuthContext)!;
  const navigate = useNavigate();
  const isEmployer = user?.id === contract?.employer.id;
  const isFreelancer = user?.id === contract?.freelancer.id;

  useEffect(() => {
    if (contractId) {
      api
        .get(`/contracts/${contractId}`)
        .then((response) => setContract(response.data.data))
        .catch((error) => {
          console.error("Error fetching contract:", error);
          toast.error("Failed to load contract.");
        });
    }
  }, [contractId]);

  const updateContractStatus = async (isAccepted: boolean) => {
    try {
      const response = await api.put(
        `/contracts/${contractId}/status?isAccepted=${isAccepted}`
      );
      const updatedContract = response.data.data;
      setContract(updatedContract);

      toast.success(isAccepted ? "Contract Accepted!" : "Contract Rejected!");

      if (isAccepted && isEmployer) {
        try {
          await api.post(`/payment/contract/${contractId}`);
          toast.success("Payment processed successfully!");
        } catch (error) {
          console.error("Error processing payment:", error);
          toast.error("Failed to process payment.");
        }
      }
    } catch (error) {
      console.error(
        "Error updating contract status or processing payment:",
        error
      );
      toast.error("Something went wrong.");
    }
  };

  if (!contract) return <Typography>Loading contract...</Typography>;

  const { employerAccepted, freelancerAccepted, status, employer, freelancer } =
    contract;

  const canEmployerAct =
    isEmployer && status === "NEGOTIATION" && !employerAccepted;

  const canFreelancerAct =
    isFreelancer &&
    status === "NEGOTIATION" &&
    employerAccepted &&
    !freelancerAccepted;

  const renderStatusChip = (accepted: boolean | null) => {
    if (accepted === true)
      return <Chip label="Accepted" color="success" size="small" />;
    if (accepted === false)
      return <Chip label="Rejected" color="error" size="small" />;
    return <Chip label="Pending" color="warning" size="small" />;
  };

  return (
    <Container maxWidth="lg" sx={{ mt: 4 }}>
      <Typography variant="h3" align="center" color="primary" gutterBottom>
        Contract Details
      </Typography>

      <Paper sx={{ p: 4, borderRadius: 3, boxShadow: 6 }}>
        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" sx={{ fontWeight: 500 }}>
            Status:{" "}
            <Chip
              label={status}
              color={status === "NEGOTIATION" ? "warning" : "success"}
              sx={{ ml: 1 }}
            />
          </Typography>
        </Box>

        <Divider sx={{ my: 3 }} />

        <Grid container spacing={3}>
          <Grid item xs={12} md={6}>
            <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
              Employer
            </Typography>
            <Typography>Name: {employer.fullName}</Typography>
            <Typography>Email: {employer.email}</Typography>
            <Box mt={1}>{renderStatusChip(employerAccepted)}</Box>
          </Grid>

          <Grid item xs={12} md={6}>
            <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
              Freelancer
            </Typography>
            <Typography>Name: {freelancer.fullName}</Typography>
            <Typography>Email: {freelancer.email}</Typography>
            <Box mt={1}>{renderStatusChip(freelancerAccepted)}</Box>
          </Grid>
        </Grid>

        <Divider sx={{ my: 3 }} />

        <Box sx={{ mt: 3 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
            Contract Period
          </Typography>
          <Typography>
            Start:{" "}
            <span style={{ color: "#1976d2" }}>
              {formatDate(contract.contractStartDate)}
            </span>
          </Typography>
          <Typography>
            End:{" "}
            <span style={{ color: "#1976d2" }}>
              {formatDate(contract.contractEndDate)}
            </span>
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
            Support & Policy
          </Typography>
          <Typography>
            Support Availability: {contract.supportAvailability}
          </Typography>
          <Typography>
            Additional Policy: {contract.additionalPolicy}
          </Typography>
        </Box>

        <Box sx={{ mt: 3 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
            Financials
          </Typography>
          <Typography>
            Deposit: <strong>${contract.depositAmount}</strong>
          </Typography>
          <Typography>
            Final Payment: <strong>${contract.finalPaymentAmount}</strong>
          </Typography>
          <Typography>Deposit Status: {contract.depositStatus}</Typography>
          <Typography>
            Final Payment Status: {contract.finalPaymentStatus}
          </Typography>
        </Box>

        {(canEmployerAct || canFreelancerAct) && (
          <Box sx={{ mt: 4, display: "flex", justifyContent: "center" }}>
            <Stack direction="row" spacing={2}>
              <Button
              sx={{ textTransform: "none" }}
                variant="contained"
                color="primary"
                onClick={() => updateContractStatus(true)}
              >
                Accept Contract
              </Button>
              <Button
              sx={{ textTransform: "none" }}
                variant="outlined"
                color="secondary"
                onClick={() => updateContractStatus(false)}
              >
                Reject Contract
              </Button>
            </Stack>
          </Box>
        )}
        {employerAccepted && freelancerAccepted && (
          <Box
            sx={{ mt: 4, display: "flex", justifyContent: "center", gap: 2 }}
          >
            <Button
            sx={{ textTransform: "none" }}
              variant="contained"
              color="primary"
              size="large"
              onClick={() => navigate(`/contract/${contract.id}/milestones`)}
            >
              View Milestones
            </Button>
          </Box>
        )}
      </Paper>
    </Container>
  );
};

export default ContractDetail;
