// src/app/pages/register/register.component.ts
// src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ToastService } from '../../services/toast.service';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule, 
    FormsModule,
    ReactiveFormsModule, 
    MatCardModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatButtonModule,
    MatSelectModule
  ],
  template: `
    <div class="container">
      <mat-card>
        <mat-card-header>
          <mat-card-title>Register</mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Full Name</mat-label>
              <input matInput formControlName="fullName" required>
              <mat-error *ngIf="registerForm.controls['fullName'].hasError('required')">
                Full Name is required
              </mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Email</mat-label>
              <input matInput formControlName="email" required>
              <mat-error *ngIf="registerForm.controls['email'].hasError('required')">
                Email is required
              </mat-error>
              <mat-error *ngIf="registerForm.controls['email'].hasError('email')">
                Please enter a valid email address
              </mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Password</mat-label>
              <input matInput type="password" formControlName="password" required>
              <mat-error *ngIf="registerForm.controls['password'].hasError('required')">
                Password is required
              </mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Confirm Password</mat-label>
              <input matInput type="password" formControlName="confirmPassword" required>
              <mat-error *ngIf="registerForm.controls['confirmPassword'].hasError('required')">
                Confirm Password is required
              </mat-error>
              <mat-error *ngIf="registerForm.controls['confirmPassword'].hasError('passwordMismatch')">
                Passwords do not match
              </mat-error>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>Role</mat-label>
              <mat-select formControlName="role" required>
                <mat-option *ngFor="let role of roles" [value]="role.value">
                  {{role.viewValue}}
                </mat-option>
              </mat-select>
            </mat-form-field>

            <button mat-raised-button color="primary" type="submit" class="full-width">
              Register
            </button>
          </form>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .container {
      display: flex;
      justify-content: center;
      padding: 20px;
    }

    mat-card {
      max-width: 400px;
      width: 100%;
    }

    .full-width {
      width: 100%;
      margin-bottom: 15px;
    }

    mat-card-title {
      margin-bottom: 20px;
    }
  `]
})
export class RegisterComponent {
  registerForm: FormGroup;
  roles = [
    { value: 'EMPLOYER', viewValue: 'Employer' },
    { value: 'FREELANCER', viewValue: 'Freelancer' }
  ];

  constructor(
    private formBuilder: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private toastService: ToastService
  ) {
    this.registerForm = this.formBuilder.group({
      fullName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
      confirmPassword: ['', Validators.required],
      role: ['EMPLOYER', Validators.required]
    }, {
      validators: this.passwordMatchValidator
    });
  }

  // Custom validator to check if passwords match
  passwordMatchValidator(form: FormGroup) {
    const password = form.get('password')?.value;
    const confirmPassword = form.get('confirmPassword')?.value;

    if (password !== confirmPassword) {
      form.get('confirmPassword')?.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    
    return null;
  }

  onSubmit(): void {
    if (this.registerForm.invalid) {
      return;
    }

    const { fullName, email, password, role } = this.registerForm.value;

    this.authService.register({ fullName, email, password, role })
      .subscribe({
        next: () => {
          this.toastService.success('Registration successful! Please upload your profile picture.');
          this.router.navigate(['/upload-profile-picture']);
        },
        error: () => {
          this.toastService.error('Registration failed!');
        }
      });
  }
}
<!-- src/app/pages/register/register.component.html -->
<div class="container">
    <mat-card>
      <mat-card-header>
        <mat-card-title>Register</mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <form [formGroup]="registerForm" (ngSubmit)="onSubmit()">
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Full Name</mat-label>
            <input matInput formControlName="fullName" required>
            <mat-error *ngIf="registerForm.controls['fullName'].hasError('required')">
              Full Name is required
            </mat-error>
          </mat-form-field>
  
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Email</mat-label>
            <input matInput formControlName="email" required>
            <mat-error *ngIf="registerForm.controls['email'].hasError('required')">
              Email is required
            </mat-error>
            <mat-error *ngIf="registerForm.controls['email'].hasError('email')">
              Please enter a valid email address
            </mat-error>
          </mat-form-field>
  
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Password</mat-label>
            <input matInput type="password" formControlName="password" required>
            <mat-error *ngIf="registerForm.controls['password'].hasError('required')">
              Password is required
            </mat-error>
          </mat-form-field>
  
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Confirm Password</mat-label>
            <input matInput type="password" formControlName="confirmPassword" required>
            <mat-error *ngIf="registerForm.controls['confirmPassword'].hasError('required')">
              Confirm Password is required
            </mat-error>
            <mat-error *ngIf="registerForm.controls['confirmPassword'].hasError('passwordMismatch')">
              Passwords do not match
            </mat-error>
          </mat-form-field>
  
          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Role</mat-label>
            <mat-select formControlName="role" required>
              <mat-option *ngFor="let role of roles" [value]="role.value">
                {{role.viewValue}}
              </mat-option>
            </mat-select>
          </mat-form-field>
  
          <button mat-raised-button color="primary" type="submit" class="full-width">
            Register
          </button>
        </form>
      </mat-card-content>
    </mat-card>
  </div>

// src/pages/Register.tsx
import { useState, useContext } from "react";
import { TextField, Button, Container, Typography, MenuItem } from "@mui/material";
import api from "../api";
import { useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";
import { toast } from "react-toastify";

const Register = () => {
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [role, setRole] = useState("EMPLOYER"); // default selection
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const navigate = useNavigate();
  const authContext = useContext(AuthContext);

  const validateEmail = (email: string) => {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (!validateEmail(email)) {
      setError("Invalid email format.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }
    try {
      const response = await api.post("/auth/register", {
        email,
        password,
        fullName,
        role,
      });
      // The API returns a payload with tokens and userResponseDTO.
      const { accessToken, refreshToken, userResponseDTO } = response.data.data;
      // Build a user object that includes tokens.
      const userData = {
        id: userResponseDTO.id, // if available
        fullName: userResponseDTO.fullName,
        email: userResponseDTO.email,
        role: userResponseDTO.role,
        cvUrl: userResponseDTO.cvUrl,
        profilePictureUrl: userResponseDTO.profilePictureUrl,
        accessToken,
        refreshToken,
      };
      if (authContext) {
        authContext.login(userData);
      }
      toast.success("Registration successful! Please upload your profile picture.");
      navigate("/upload-profile-picture", { replace: true });
    } catch (error) {
      setError("Registration failed!");
    }
  };

  return (
    <Container maxWidth="xs">
      <Typography variant="h4">Register</Typography>
      {error && <Typography color="error">{error}</Typography>}
      <form onSubmit={handleSubmit}>
        <TextField
          fullWidth
          label="Full Name"
          margin="normal"
          onChange={(e) => setFullName(e.target.value)}
          required
        />
        <TextField
          fullWidth
          label="Email"
          type="email"
          margin="normal"
          onChange={(e) => setEmail(e.target.value)}
          required
        />
        <TextField
          fullWidth
          label="Password"
          type="password"
          margin="normal"
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <TextField
          fullWidth
          label="Confirm Password"
          type="password"
          margin="normal"
          onChange={(e) => setConfirmPassword(e.target.value)}
          required
        />
        <TextField
          select
          fullWidth
          label="Role"
          margin="normal"
          value={role}
          onChange={(e) => setRole(e.target.value)}
        >
          <MenuItem value="EMPLOYER">Employer</MenuItem>
          <MenuItem value="FREELANCER">Freelancer</MenuItem>
        </TextField>
        <Button fullWidth variant="contained" color="primary" type="submit">
          Register
        </Button>
      </form>
    </Container>
  );
};

export default Register;
