// src/app/components/header/header.component.ts
// src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { User } from '../../models/user';
import { CommonModule } from '@angular/common';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatMenuModule
  ],
  template: `
    <mat-toolbar class="header-toolbar">
      <img src="assets/images/skilllease-logo.png" alt="Skilllease Logo" class="logo" (click)="navigateTo('/')" />
      
      <span class="spacer"></span>
      
      <!-- Desktop Menu -->
      <div class="desktop-menu">
        <ng-container *ngIf="user">
          <!-- Dashboard link for all logged in users -->
          <button mat-button (click)="navigateTo('/dashboard')">
            <mat-icon>dashboard</mat-icon>
            Dashboard
          </button>
          
          <!-- Employer Menu Items -->
          <ng-container *ngIf="user.role === 'EMPLOYER'">
            <button mat-button (click)="navigateTo('/post-job')">
              <mat-icon>add_circle</mat-icon>
              Post Job
            </button>
            <button mat-button (click)="navigateTo('/employer-jobs')">
              <mat-icon>work</mat-icon>
              My Jobs
            </button>
            <button mat-button (click)="navigateTo('/my-contracts')">
              <mat-icon>description</mat-icon>
              My Contracts
            </button>
          </ng-container>
          
          <!-- Freelancer Menu Items -->
          <ng-container *ngIf="user.role === 'FREELANCER'">
            <button mat-button (click)="navigateTo('/post-service')">
              <mat-icon>build</mat-icon>
              Post Service
            </button>
            <button mat-button (click)="navigateTo('/my-services')">
              <mat-icon>build</mat-icon>
              My Services
            </button>
            <button mat-button (click)="navigateTo('/my-contracts')">
              <mat-icon>work</mat-icon>
              My Contracts
            </button>
          </ng-container>
          
          <!-- Wallet Button -->
          <button mat-button (click)="navigateTo('/recharge')">
            <mat-icon>account_balance_wallet</mat-icon>
            {{ walletBalance ? (walletBalance | number) + '₫' : 'Loading...' }}
          </button>
          
          <!-- User Menu -->
          <button mat-button [matMenuTriggerFor]="userMenu">
            <div *ngIf="user.profilePictureUrl; else initialAvatar">
              <img [src]="user.profilePictureUrl" alt="{{user.fullName}}" class="user-avatar" />
            </div>
            <ng-template #initialAvatar>
              <div class="initial-avatar">{{ getUserInitials() }}</div>
            </ng-template>
            {{ user.fullName }}
          </button>
          <mat-menu #userMenu="matMenu">
            <button mat-menu-item (click)="logout()">
              <mat-icon>logout</mat-icon>
              Logout
            </button>
          </mat-menu>
        </ng-container>

        <!-- Login/Register when not logged in -->
        <ng-container *ngIf="!user">
          <button mat-button (click)="navigateTo('/login')">
            <mat-icon>login</mat-icon>
            Login
          </button>
          <button mat-button (click)="navigateTo('/register')">
            <mat-icon>person_add</mat-icon>
            Register
          </button>
        </ng-container>
      </div>
      
      <!-- Mobile Menu Button -->
      <button mat-icon-button [matMenuTriggerFor]="mobileMenu" class="mobile-menu-button">
        <mat-icon>menu</mat-icon>
      </button>
      
      <!-- Mobile Menu -->
      <mat-menu #mobileMenu="matMenu">
        <ng-container *ngIf="user">
          <!-- Dashboard link for mobile -->
          <button mat-menu-item (click)="navigateTo('/dashboard')">Dashboard</button>
          
          <!-- Employer Menu Items -->
          <ng-container *ngIf="user.role === 'EMPLOYER'">
            <button mat-menu-item (click)="navigateTo('/post-job')">Post Job</button>
            <button mat-menu-item (click)="navigateTo('/employer-jobs')">My Jobs</button>
          </ng-container>
          
          <!-- Freelancer Menu Items -->
          <ng-container *ngIf="user.role === 'FREELANCER'">
            <button mat-menu-item (click)="navigateTo('/post-service')">Post Service</button>
            <button mat-menu-item (click)="navigateTo('/my-services')">My Services</button>
          </ng-container>
          
          <button mat-menu-item (click)="navigateTo('/recharge')">Recharge</button>
          <button mat-menu-item (click)="logout()">Logout</button>
        </ng-container>

        <!-- Login/Register when not logged in (Mobile) -->
        <ng-container *ngIf="!user">
          <button mat-menu-item (click)="navigateTo('/login')">Login</button>
          <button mat-menu-item (click)="navigateTo('/register')">Register</button>
        </ng-container>
      </mat-menu>
    </mat-toolbar>
  `,
  styles: [`
    .header-toolbar {
      background: linear-gradient(45deg, #2196F3 30%, #21CBF3 90%);
      box-shadow: 0 3px 5px -1px rgba(0,0,0,.2), 0 6px 10px 0 rgba(0,0,0,.14), 0 1px 18px 0 rgba(0,0,0,.12);
      position: sticky;
      top: 0;
      z-index: 1000;
    }

    .logo {
      height: 80px;
      cursor: pointer;
    }

    .spacer {
      flex: 1 1 auto;
    }

    .user-avatar {
      width: 35px;
      height: 35px;
      border-radius: 50%;
      margin-right: 8px;
      vertical-align: middle;
    }

    .initial-avatar {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 35px;
      height: 35px;
      border-radius: 50%;
      background-color: #3f51b5;
      color: white;
      margin-right: 8px;
      vertical-align: middle;
    }

    .desktop-menu {
      display: flex;
      align-items: center;
    }
    
    .desktop-menu button {
      margin: 0 4px;
    }
    
    .desktop-menu button mat-icon {
      margin-right: 4px;
    }

    .mobile-menu-button {
      display: none;
    }

    /* Media query for mobile devices */
    @media (max-width: 768px) {
      .desktop-menu {
        display: none;
      }
      
      .mobile-menu-button {
        display: block;
      }
    }
  `]
})
export class HeaderComponent implements OnInit {
  user: User | null = null;
  walletBalance: number | null = null;

  constructor(
    private authService: AuthService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.authService.currentUser.subscribe(user => {
      this.user = user;
      // For now, we'll just set a placeholder wallet balance
      // In reality, you'd fetch this from a wallet service
      this.walletBalance = 1000;
    });
  }

  logout(): void {
    this.authService.logout();
  }

  navigateTo(route: string): void {
    this.router.navigate([route]);
  }

  // Returns user initials for the avatar
  getUserInitials(): string {
    if (this.user?.fullName) {
      return this.user.fullName
        .split(' ')
        .map(name => name.charAt(0))
        .join('');
    }
    return '';
  }
}
<!-- src/app/components/header/header.component.html -->
<mat-toolbar class="header-toolbar">
    <img src="assets/images/skilllease-logo.png" alt="Skilllease Logo" class="logo" (click)="navigateTo('/')" />
    
    <span class="spacer"></span>
    
    <!-- Desktop Menu -->
    <div class="desktop-menu">
      <ng-container *ngIf="user">
        <!-- Employer Menu Items -->
        <ng-container *ngIf="user.role === 'EMPLOYER'">
          <button mat-button (click)="navigateTo('/post-job')">
            <mat-icon>work</mat-icon>
            Post Job
          </button>
          <button mat-button (click)="navigateTo('/employer-jobs')">
            <mat-icon>work</mat-icon>
            My Jobs
          </button>
          <button mat-button (click)="navigateTo('/my-contracts')">
            <mat-icon>work</mat-icon>
            My Contracts
          </button>
        </ng-container>
        
        <!-- Freelancer Menu Items -->
        <ng-container *ngIf="user.role === 'FREELANCER'">
          <button mat-button (click)="navigateTo('/post-service')">
            <mat-icon>build</mat-icon>
            Post Service
          </button>
          <button mat-button (click)="navigateTo('/my-services')">
            <mat-icon>build</mat-icon>
            My Services
          </button>
          <button mat-button (click)="navigateTo('/my-contracts')">
            <mat-icon>work</mat-icon>
            My Contracts
          </button>
        </ng-container>
        
        <!-- Wallet Button -->
        <button mat-button (click)="navigateTo('/recharge')">
          <mat-icon>account_balance_wallet</mat-icon>
          {{ walletBalance ? (walletBalance | number) + '₫' : 'Loading...' }}
        </button>
        
        <!-- User Menu -->
        <button mat-button [matMenuTriggerFor]="userMenu">
          <div *ngIf="user.profilePictureUrl; else initialAvatar">
            <img [src]="user.profilePictureUrl" alt="{{user.fullName}}" class="user-avatar" />
          </div>
          <ng-template #initialAvatar>
            <div class="initial-avatar">{{ getUserInitials() }}</div>
          </ng-template>
          {{ user.fullName }}
        </button>
        <mat-menu #userMenu="matMenu">
          <button mat-menu-item (click)="logout()">
            <mat-icon>logout</mat-icon>
            Logout
          </button>
        </mat-menu>
      </ng-container>
    </div>
    
    <!-- Mobile Menu Button -->
    <button mat-icon-button [matMenuTriggerFor]="mobileMenu" class="mobile-menu-button">
      <mat-icon>menu</mat-icon>
    </button>
    
    <!-- Mobile Menu -->
    <mat-menu #mobileMenu="matMenu">
      <ng-container *ngIf="user">
        <!-- Employer Menu Items -->
        <ng-container *ngIf="user.role === 'EMPLOYER'">
          <button mat-menu-item (click)="navigateTo('/post-job')">Post Job</button>
          <button mat-menu-item (click)="navigateTo('/employer-jobs')">My Jobs</button>
        </ng-container>
        
        <!-- Freelancer Menu Items -->
        <ng-container *ngIf="user.role === 'FREELANCER'">
          <button mat-menu-item (click)="navigateTo('/post-service')">Post Service</button>
          <button mat-menu-item (click)="navigateTo('/my-services')">My Services</button>
        </ng-container>
        
        <button mat-menu-item (click)="navigateTo('/recharge')">Recharge</button>
        <button mat-menu-item (click)="logout()">Logout</button>
      </ng-container>
    </mat-menu>
  </mat-toolbar>

// src/components/Header.tsx
import React, { useState, useContext } from "react";
import {
  AppBar,
  Toolbar,
  Button,
  Avatar,
  Box,
  Typography,
  IconButton,
  Menu,
  MenuItem,
} from "@mui/material";
import { useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";
import logo from "../assets/skilllease-logo.png";
import MenuIcon from "@mui/icons-material/Menu";
import WorkIcon from "@mui/icons-material/Work";
import BuildIcon from "@mui/icons-material/Build";
import LogoutIcon from "@mui/icons-material/Logout";
import AccountBalanceWalletIcon from "@mui/icons-material/AccountBalanceWallet";
import AccountCircleIcon from "@mui/icons-material/AccountCircle"; // For clickable name
import { useWallet } from "../utils/useWallet";

const Header = () => {
  const auth = useContext(AuthContext);
  const navigate = useNavigate();

  if (!auth) {
    throw new Error(
      "AuthContext is missing. Wrap your component with AuthProvider."
    );
  }

  const { user, logout } = auth;
  const wallet = useWallet();

  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
  const [menuAnchorEl, setMenuAnchorEl] = useState<null | HTMLElement>(null);
  const open = Boolean(anchorEl);
  const openMenu = Boolean(menuAnchorEl);

  const handleMenuOpen = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };

  const handleMenuClose = () => {
    setAnchorEl(null);
  };

  const handleUserMenuOpen = (event: React.MouseEvent<HTMLElement>) => {
    setMenuAnchorEl(event.currentTarget);
  };

  const handleUserMenuClose = () => {
    setMenuAnchorEl(null);
  };

  // Returns an Avatar using profilePictureUrl if available or initials.
  const getUserAvatar = () => {
    if (user?.profilePictureUrl) {
      return <Avatar alt={user.fullName} src={user.profilePictureUrl} />;
    }
    if (user?.fullName) {
      const initials = user.fullName
        .split(" ")
        .map((name) => name.charAt(0))
        .join("");
      return <Avatar>{initials}</Avatar>;
    }
    return null;
  };

  return (
    <AppBar
      position="sticky"
      sx={{
        background: "linear-gradient(45deg, #2196F3 30%, #21CBF3 90%)",
        boxShadow: 3,
      }}
    >
      <Toolbar>
        <Box
          component="img"
          src={logo}
          alt="Skilllease Logo"
          sx={{ height: 80, cursor: "pointer" }}
          onClick={() => navigate("/")}
        />
        <Box sx={{ flexGrow: 1 }} />

        <Box
          sx={{
            display: { xs: "none", md: "flex" },
            alignItems: "center",
            gap: 2,
          }}
        >
          {user && user.role === "EMPLOYER" && (
            <>
              <Button
                color="inherit"
                startIcon={<WorkIcon />}
                sx={{ textTransform: "none" }}
                onClick={() => navigate("/post-job")}
              >
                Post Job
              </Button>
              <Button
                color="inherit"
                startIcon={<WorkIcon />}
                sx={{ textTransform: "none" }}
                onClick={() => navigate("/employer-jobs")}
              >
                My Jobs
              </Button>
              <Button
                color="inherit"
                startIcon={<WorkIcon />}
                sx={{ textTransform: "none" }}
                onClick={() => navigate("/my-contracts")}
              >
                My Contracts
              </Button>
            </>
          )}
          {user && user.role === "FREELANCER" && (
            <>
              <Button
                color="inherit"
                startIcon={<BuildIcon />}
                sx={{ textTransform: "none" }}
                onClick={() => navigate("/post-service")}
              >
                Post Service
              </Button>
              <Button
                color="inherit"
                startIcon={<BuildIcon />}
                sx={{ textTransform: "none" }}
                onClick={() => navigate("/my-services")}
              >
                My Services
              </Button>
              <Button
                color="inherit"
                startIcon={<WorkIcon />}
                sx={{ textTransform: "none" }}
                onClick={() => navigate("/my-contracts")}
              >
                My Contracts
              </Button>
            </>
          )}
          <Button
            color="inherit"
            startIcon={<AccountBalanceWalletIcon />}
            onClick={() => navigate("/recharge")}
          >
            {wallet ? `${wallet.balance.toLocaleString()}₫` : "Loading..."}
          </Button>

          {user && (
            <Box>
              <Button
                color="inherit"
                startIcon={getUserAvatar() || <AccountCircleIcon />}
                onClick={handleUserMenuOpen}
                sx={{ textTransform: "none" }}
              >
                {user.fullName}
              </Button>
              <Menu
                anchorEl={menuAnchorEl}
                open={openMenu}
                onClose={handleUserMenuClose}
                anchorOrigin={{ vertical: "bottom", horizontal: "right" }}
                transformOrigin={{ vertical: "top", horizontal: "right" }}
              >
                <MenuItem onClick={logout}>Logout</MenuItem>
              </Menu>
            </Box>
          )}
        </Box>

        {/* Mobile Navigation */}
        <Box sx={{ display: { xs: "flex", md: "none" } }}>
          <IconButton color="inherit" onClick={handleMenuOpen} size="large">
            <MenuIcon />
          </IconButton>
          <Menu
            anchorEl={anchorEl}
            open={open}
            onClose={handleMenuClose}
            anchorOrigin={{ vertical: "bottom", horizontal: "right" }}
            transformOrigin={{ vertical: "top", horizontal: "right" }}
          >
            {user && user.role === "EMPLOYER" && (
              <Box>
                <MenuItem onClick={() => navigate("/post-job")}>
                  Post Job
                </MenuItem>
                <MenuItem onClick={() => navigate("/employer-jobs")}>
                  My Jobs
                </MenuItem>
              </Box>
            )}
            {user && user.role === "FREELANCER" && (
              <Box>
                <MenuItem onClick={() => navigate("/post-service")}>
                  Post Service
                </MenuItem>
                <MenuItem onClick={() => navigate("/my-services")}>
                  My Services
                </MenuItem>
              </Box>
            )}
            <MenuItem onClick={() => navigate("/recharge")}>Recharge</MenuItem>
            {user && <MenuItem onClick={logout}>Logout</MenuItem>}
          </Menu>
        </Box>
      </Toolbar>
    </AppBar>
  );
};

export default Header;
